name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    name: Increment Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      v-version: ${{ steps.version.outputs.v-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: calver
          increment: patch
          tag_prefix: v

      - name: Create tag
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.version.outputs.v-version }}',
              sha: context.sha
            })

  release:
    name: Build and Release
    needs:
      - tag
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ needs.tag.outputs.v-version }}
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAPS_KEY: ${{ secrets.TAPS_KEY }}
